// Mocks generated by Mockito 5.4.6 from annotations
// in vista/test/integration/media_upload_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vista/models/api_response.dart' as _i2;
import 'package:vista/models/media_upload.dart' as _i5;
import 'package:vista/services/media_api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MediaApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaApiService extends _i1.Mock implements _i3.MediaApiService {
  MockMediaApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i5.MediaSignResponse>> getSignedUploadParams({
    required String? filename,
    required String? mimeType,
    required String? studentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSignedUploadParams, [], {
              #filename: filename,
              #mimeType: mimeType,
              #studentId: studentId,
            }),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i5.MediaSignResponse>>.value(
                  _FakeApiResponse_0<_i5.MediaSignResponse>(
                    this,
                    Invocation.method(#getSignedUploadParams, [], {
                      #filename: filename,
                      #mimeType: mimeType,
                      #studentId: studentId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.MediaSignResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.CloudinaryUploadResponse>> uploadToCloudinary(
    _i6.XFile? file,
    _i5.MediaSignResponse? signParams, {
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadToCloudinary,
              [file, signParams],
              {#onProgress: onProgress},
            ),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i5.CloudinaryUploadResponse>>.value(
                  _FakeApiResponse_0<_i5.CloudinaryUploadResponse>(
                    this,
                    Invocation.method(
                      #uploadToCloudinary,
                      [file, signParams],
                      {#onProgress: onProgress},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.CloudinaryUploadResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.CloudinaryUploadResponse>> uploadFile(
    _i6.XFile? file,
    String? studentId, {
    dynamic Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [file, studentId],
              {#onProgress: onProgress},
            ),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i5.CloudinaryUploadResponse>>.value(
                  _FakeApiResponse_0<_i5.CloudinaryUploadResponse>(
                    this,
                    Invocation.method(
                      #uploadFile,
                      [file, studentId],
                      {#onProgress: onProgress},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.CloudinaryUploadResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> validateFile(_i6.XFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#validateFile, [file]),
            returnValue: _i4.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#validateFile, [file]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<void>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
