// Mocks generated by Mockito 5.4.6 from annotations
// in vista/test/services/api_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:vista/models/api_response.dart' as _i2;
import 'package:vista/models/user.dart' as _i6;
import 'package:vista/services/api_service.dart' as _i7;
import 'package:vista/services/auth_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.User?>.empty(),
          )
          as _i4.Stream<_i5.User?>);

  @override
  bool get isSignedIn =>
      (super.noSuchMethod(Invocation.getter(#isSignedIn), returnValue: false)
          as bool);

  @override
  _i4.Future<_i2.ApiResponse<_i6.User>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i2.ApiResponse<_i6.User>>.value(
              _FakeApiResponse_0<_i6.User>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i6.User>>);

  @override
  _i4.Future<_i2.ApiResponse<_i6.User>> linkStudentId(String? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#linkStudentId, [studentId]),
            returnValue: _i4.Future<_i2.ApiResponse<_i6.User>>.value(
              _FakeApiResponse_0<_i6.User>(
                this,
                Invocation.method(#linkStudentId, [studentId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i6.User>>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getJwtToken() =>
      (super.noSuchMethod(
            Invocation.method(#getJwtToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i6.User?> getStoredUser() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredUser, []),
            returnValue: _i4.Future<_i6.User?>.value(),
          )
          as _i4.Future<_i6.User?>);

  @override
  _i4.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i7.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setJwtToken(String? token) => super.noSuchMethod(
    Invocation.method(#setJwtToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.ApiResponse<Map<String, dynamic>>> get(
    String? endpoint, {
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint], {#queryParams: queryParams}),
            returnValue:
                _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #get,
                      [endpoint],
                      {#queryParams: queryParams},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResponse<Map<String, dynamic>>> post(
    String? endpoint,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#post, [endpoint, data]),
            returnValue:
                _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#post, [endpoint, data]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResponse<Map<String, dynamic>>> put(
    String? endpoint,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#put, [endpoint, data]),
            returnValue:
                _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#put, [endpoint, data]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResponse<Map<String, dynamic>>> patch(
    String? endpoint,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [endpoint, data]),
            returnValue:
                _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#patch, [endpoint, data]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResponse<Map<String, dynamic>>> delete(String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint]),
            returnValue:
                _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#delete, [endpoint]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResponse<Map<String, dynamic>>> getPublic(
    String? endpoint, {
    Map<String, String>? queryParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPublic,
              [endpoint],
              {#queryParams: queryParams},
            ),
            returnValue:
                _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #getPublic,
                      [endpoint],
                      {#queryParams: queryParams},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResponse<Map<String, dynamic>>> postPublic(
    String? endpoint,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#postPublic, [endpoint, data]),
            returnValue:
                _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>.value(
                  _FakeApiResponse_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#postPublic, [endpoint, data]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<Map<String, dynamic>>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
