// Mocks generated by Mockito 5.4.6 from annotations
// in vista/test/providers/chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vista/models/user.dart' as _i12;
import 'package:vista/services/api_client.dart' as _i10;
import 'package:vista/services/auth_service.dart' as _i9;
import 'package:vista/services/chat_api_service.dart' as _i8;
import 'package:vista/services/media_api_service.dart' as _i6;
import 'package:vista/services/notifications_api_service.dart' as _i7;
import 'package:vista/services/posts_api_service.dart' as _i2;
import 'package:vista/services/stories_api_service.dart' as _i3;
import 'package:vista/services/topics_api_service.dart' as _i4;
import 'package:vista/services/users_api_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePostsApiService_0 extends _i1.SmartFake
    implements _i2.PostsApiService {
  _FakePostsApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStoriesApiService_1 extends _i1.SmartFake
    implements _i3.StoriesApiService {
  _FakeStoriesApiService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopicsApiService_2 extends _i1.SmartFake
    implements _i4.TopicsApiService {
  _FakeTopicsApiService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersApiService_3 extends _i1.SmartFake
    implements _i5.UsersApiService {
  _FakeUsersApiService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMediaApiService_4 extends _i1.SmartFake
    implements _i6.MediaApiService {
  _FakeMediaApiService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationsApiService_5 extends _i1.SmartFake
    implements _i7.NotificationsApiService {
  _FakeNotificationsApiService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatApiService_6 extends _i1.SmartFake
    implements _i8.ChatApiService {
  _FakeChatApiService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_7 extends _i1.SmartFake implements _i9.AuthService {
  _FakeAuthService_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i10.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostsApiService get posts =>
      (super.noSuchMethod(
            Invocation.getter(#posts),
            returnValue: _FakePostsApiService_0(
              this,
              Invocation.getter(#posts),
            ),
          )
          as _i2.PostsApiService);

  @override
  _i3.StoriesApiService get stories =>
      (super.noSuchMethod(
            Invocation.getter(#stories),
            returnValue: _FakeStoriesApiService_1(
              this,
              Invocation.getter(#stories),
            ),
          )
          as _i3.StoriesApiService);

  @override
  _i4.TopicsApiService get topics =>
      (super.noSuchMethod(
            Invocation.getter(#topics),
            returnValue: _FakeTopicsApiService_2(
              this,
              Invocation.getter(#topics),
            ),
          )
          as _i4.TopicsApiService);

  @override
  _i5.UsersApiService get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeUsersApiService_3(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i5.UsersApiService);

  @override
  _i6.MediaApiService get media =>
      (super.noSuchMethod(
            Invocation.getter(#media),
            returnValue: _FakeMediaApiService_4(
              this,
              Invocation.getter(#media),
            ),
          )
          as _i6.MediaApiService);

  @override
  _i7.NotificationsApiService get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _FakeNotificationsApiService_5(
              this,
              Invocation.getter(#notifications),
            ),
          )
          as _i7.NotificationsApiService);

  @override
  _i8.ChatApiService get chat =>
      (super.noSuchMethod(
            Invocation.getter(#chat),
            returnValue: _FakeChatApiService_6(this, Invocation.getter(#chat)),
          )
          as _i8.ChatApiService);

  @override
  _i9.AuthService get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuthService_7(this, Invocation.getter(#auth)),
          )
          as _i9.AuthService);

  @override
  _i11.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void setJwtToken(String? token) => super.noSuchMethod(
    Invocation.method(#setJwtToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearJwtToken() => super.noSuchMethod(
    Invocation.method(#clearJwtToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i12.User?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i11.Future<_i12.User?>.value(),
          )
          as _i11.Future<_i12.User?>);

  @override
  _i11.Future<void> refreshAuth() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAuth, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool> healthCheck() =>
      (super.noSuchMethod(
            Invocation.method(#healthCheck, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
