// Mocks generated by Mockito 5.4.6 from annotations
// in vista/test/providers/feed_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vista/models/api_response.dart' as _i2;
import 'package:vista/models/comment.dart' as _i6;
import 'package:vista/models/post.dart' as _i5;
import 'package:vista/services/posts_api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsApiService extends _i1.Mock implements _i3.PostsApiService {
  MockPostsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<_i3.PostsFeedResponse>> getPosts({
    String? cursor,
    int? limit = 20,
    String? visibility = 'public',
    String? authorStudentId,
    List<String>? tags,
    String? search,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {
              #cursor: cursor,
              #limit: limit,
              #visibility: visibility,
              #authorStudentId: authorStudentId,
              #tags: tags,
              #search: search,
            }),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i3.PostsFeedResponse>>.value(
                  _FakeApiResponse_0<_i3.PostsFeedResponse>(
                    this,
                    Invocation.method(#getPosts, [], {
                      #cursor: cursor,
                      #limit: limit,
                      #visibility: visibility,
                      #authorStudentId: authorStudentId,
                      #tags: tags,
                      #search: search,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.PostsFeedResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Post>> createPost(
    _i5.CreatePostRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.Post>>.value(
              _FakeApiResponse_0<_i5.Post>(
                this,
                Invocation.method(#createPost, [request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.Post>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.Post>> getPost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [postId]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.Post>>.value(
              _FakeApiResponse_0<_i5.Post>(
                this,
                Invocation.method(#getPost, [postId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.Post>>);

  @override
  _i4.Future<_i2.ApiResponse<_i3.LikePostResponse>> likePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [postId]),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i3.LikePostResponse>>.value(
                  _FakeApiResponse_0<_i3.LikePostResponse>(
                    this,
                    Invocation.method(#likePost, [postId]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.LikePostResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<_i3.CommentResponse>> commentOnPost(
    String? postId,
    _i6.CreateCommentRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#commentOnPost, [postId, request]),
            returnValue: _i4.Future<_i2.ApiResponse<_i3.CommentResponse>>.value(
              _FakeApiResponse_0<_i3.CommentResponse>(
                this,
                Invocation.method(#commentOnPost, [postId, request]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.CommentResponse>>);

  @override
  _i4.Future<_i2.ApiResponse<_i3.CommentsResponse>> getPostComments(
    String? postId, {
    int? limit = 50,
    String? sortBy = 'newest',
    String? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getPostComments,
              [postId],
              {
                #limit: limit,
                #sortBy: sortBy,
                #parentCommentId: parentCommentId,
              },
            ),
            returnValue:
                _i4.Future<_i2.ApiResponse<_i3.CommentsResponse>>.value(
                  _FakeApiResponse_0<_i3.CommentsResponse>(
                    this,
                    Invocation.method(
                      #getPostComments,
                      [postId],
                      {
                        #limit: limit,
                        #sortBy: sortBy,
                        #parentCommentId: parentCommentId,
                      },
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponse<_i3.CommentsResponse>>);
}
