// Mocks generated by Mockito 5.4.6 from annotations
// in vista/test/screens/stories_viewer_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:vista/models/story.dart' as _i3;
import 'package:vista/providers/stories_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [StoriesProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoriesProvider extends _i1.Mock implements _i2.StoriesProvider {
  MockStoriesProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Story> get stories =>
      (super.noSuchMethod(
            Invocation.getter(#stories),
            returnValue: <_i3.Story>[],
          )
          as List<_i3.Story>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isCreatingStory =>
      (super.noSuchMethod(
            Invocation.getter(#isCreatingStory),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasMore =>
      (super.noSuchMethod(Invocation.getter(#hasMore), returnValue: false)
          as bool);

  @override
  Map<String, List<_i3.Story>> get storiesByAuthor =>
      (super.noSuchMethod(
            Invocation.getter(#storiesByAuthor),
            returnValue: <String, List<_i3.Story>>{},
          )
          as Map<String, List<_i3.Story>>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadInitialStories() =>
      (super.noSuchMethod(
            Invocation.method(#loadInitialStories, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refreshStories() =>
      (super.noSuchMethod(
            Invocation.method(#refreshStories, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> loadMoreStories() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreStories, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> createStoryFromCamera() =>
      (super.noSuchMethod(
            Invocation.method(#createStoryFromCamera, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createStoryFromGallery() =>
      (super.noSuchMethod(
            Invocation.method(#createStoryFromGallery, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createStoryFromVideo() =>
      (super.noSuchMethod(
            Invocation.method(#createStoryFromVideo, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> viewStory(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#viewStory, [storyId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
