// Mocks generated by Mockito 5.4.6 from annotations
// in vista/test/screens/topics_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:vista/models/comment.dart' as _i4;
import 'package:vista/models/topic.dart' as _i3;
import 'package:vista/models/user.dart' as _i9;
import 'package:vista/providers/auth_provider.dart' as _i8;
import 'package:vista/providers/topics_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TopicsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopicsProvider extends _i1.Mock implements _i2.TopicsProvider {
  MockTopicsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Topic> get topics =>
      (super.noSuchMethod(
            Invocation.getter(#topics),
            returnValue: <_i3.Topic>[],
          )
          as List<_i3.Topic>);

  @override
  bool get isLoadingTopics =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingTopics),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasMoreTopics =>
      (super.noSuchMethod(Invocation.getter(#hasMoreTopics), returnValue: false)
          as bool);

  @override
  List<_i4.Comment> get currentTopicComments =>
      (super.noSuchMethod(
            Invocation.getter(#currentTopicComments),
            returnValue: <_i4.Comment>[],
          )
          as List<_i4.Comment>);

  @override
  bool get isLoadingTopic =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingTopic),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoadingComments =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingComments),
            returnValue: false,
          )
          as bool);

  @override
  String get sortBy =>
      (super.noSuchMethod(
            Invocation.getter(#sortBy),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#sortBy),
            ),
          )
          as String);

  @override
  List<String> get selectedTags =>
      (super.noSuchMethod(
            Invocation.getter(#selectedTags),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadTopics({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#loadTopics, [], {#refresh: refresh}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> createTopic(_i3.CreateTopicRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createTopic, [request]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> loadTopic(String? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#loadTopic, [topicId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> voteTopic(String? topicId, _i3.VoteType? voteType) =>
      (super.noSuchMethod(
            Invocation.method(#voteTopic, [topicId, voteType]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> loadTopicComments(String? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#loadTopicComments, [topicId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> addComment(
    String? topicId,
    _i4.CreateCommentRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [topicId, request]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void setSortBy(String? sortBy) => super.noSuchMethod(
    Invocation.method(#setSortBy, [sortBy]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedTags(List<String>? tags) => super.noSuchMethod(
    Invocation.method(#setSelectedTags, [tags]),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void clearCurrentTopic() => super.noSuchMethod(
    Invocation.method(#clearCurrentTopic, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i8.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> linkStudentId(String? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#linkStudentId, [studentId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUser(_i9.User? updatedUser) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [updatedUser]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLoading(bool? loading) => super.noSuchMethod(
    Invocation.method(#setLoading, [loading]),
    returnValueForMissingStub: null,
  );

  @override
  void setError(String? error) => super.noSuchMethod(
    Invocation.method(#setError, [error]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
